EncuestaRickMorty/EncuestaRickMorty/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # La siguente línea es la que se agrega:
    path('encuesta/', include('encuesta.urls'))
]

EncuestaRickMorty/encuesta/urls.py
from django.urls import path

from . import views

app_name = "encuesta"

urlpatterns = [
    # Ejemplo de la ruta: /encuesta/
    path('/', views.IndexView.as_view(), name='index'),
    # Ejemplo de la ruta: /encuesta/detalle/5/
    path('/detalle/<int:pk>/', views.DetalleView.as_view(), name='detalle'),
    # Ejemplo de la ruta: /encuesta/resultado/5
    path('/resultado/<int:pk>/', views.ResultadoView.as_view(), name='resultado'),
    # Ejemplo de la ruta: /encuesta/votos/5
    path('/votos/<int:pk>/', views.ResultadoView.as_view(), name='voto')
]

EncuestaRickMorty/encuesta/models.py
from django.db import models


class Pregunta(models.Model):
    pregunta_texto = models.CharField(max_length=200)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.pregunta_texto


class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.opcion_texto

EncuestaRickMorty/encuesta/views.py
from django.shortcuts import render, get_object_or_404

# Construiremos un BodyResponse de una petición
from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse
from django.views import generic

from .models import Pregunta, Opcion


# GENERIC VIEWS (Class Based Views)

class IndexView(generic.ListView):
    template_name = "encuesta/index.html"
    context_object_name = "lista_de_preguntas"


class DetalleView(generic.DetailView):
    model = Pregunta
    template_name = "encuesta/detalle.html"


class ResultadoView(generic.DetailView):
    model = Pregunta
    template_name = "encuesta/resultado.html"


def voto(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)

    try:
        opcion_selecionada = pregunta.pregunta_set.get(
            pk=request.POST["choice"])

    except (KeyError, Opcion.DoesNotExist):
        return render(request=request,
                      template_name="encuesta/detalle.html",
                      context={
                          "pregunta": pregunta,
                          "error_message": "¡No elegiste una respuesta!"
                      })

    else:
        opcion_selecionada.votes += 1
        opcion_selecionada.save()

        return HttpResponseRedirect(reverse("encuesta:resultado", args=(pregunta_id,)))


# FUNCTION BASED VIEWS:
# Definimos la respuesta del request

# def index(request):
#     return render(request=request,
#                   template_name="encuesta/index.html",
#                   context={
#                       "lista_de_preguntas": Pregunta.objects.all()
#                   }
#                   )


# def details(request, pregunta_id):
#     pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
#     return render(request=request,
#                   template_name="encuesta/detalle.html",
#                   context={
#                       "pregunta": pregunta
#                   })


# def results(request, pregunta_id):
#     pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
#     return render(request=request,
#                   template_name="encuesta/resultado.html",
#                   context={
#                       "pregunta": pregunta
#                   })

EncuestaRickMorty/encuesta/templates/encuesta/detalle.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'encuesta/style.css' %}">
    <link rel="stylesheet" href="{% static 'encuesta/details.css' %}">
    <title>{{ pregunta.pregunta_texto}}</title>
</head>
<body>
    <form action="{% url 'encuesta:votos' pregunta.id %}" method="post">
        <!-- esta la siguiente linea nos protegernos del hackeo csrf en formularios-->
        {% csrf_token %} 
    
        <fieldset>
    
            <legend>
                <h1>{{ pregunta.pregunta_texto }}</h1>
            </legend>
    
            {% if error_message %}
                <p><strong>{{ error_message  }}</strong></p>
            {% endif %}
    
            {% for opcion in pregunta.opcion_set.all %}
                <input type="radio" id="opcion{{ forloop.counter }}" name="opcion" value={{opcion.id}}>
                <label for="opcion{{ forloop.counter}}">{{ opcion.opcion_texto }}</label><br>
            {% endfor %}
    
        </fieldset>
    
        <input type="submit" value="Votar">
    
    </form>
</body>
</html>

EncuestaRickMorty/encuesta/templates/encuesta/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'encuesta/reset.css' %}">
    <link rel="stylesheet" href="{% static 'encuesta/style.css' %}">
    <title>Encuesta Rick y Morty</title>
  </head>
  <body>

    <header>
      <h1>Encuesta sobre los personajes de Rick y Morty</h1>
    </header>

    <main>
        {% if lista_de_preguntas %}
        <ul>
            {% for pregunta in lista_de_preguntas %}
                <li>
                <a href="{% url 'encuesta:detalle' pregunta.id %}">{{ pregunta.pregunta_texto }}</a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No hay una encuesta disponible. :(</p>
        {% endif %}
    </main>
    <footer>
        <a href="#">Mi página</a>
        <a href="#">Contacto</a>
        <a href="#">Politica de privacidad</a>
        <a href="#">Terminos y condiciones</a>
    </footer>
  </body>
</html>

EncuestaRickMorty/encuesta/templates/encuesta/resultado.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Resultados</title>
  </head>
  <body>
    <h1>{{ pregunta.pregunta_texto }}</h1>
    <ul>
      {% for opcion in pregunta.opcion_set.all %}
      <li>
        {{ opcion.opcion_texto }} ----- {{ opcion.votos }} voto{{ opcion.votos|pluralize }}
      </li>
      {% endfor %}
    </ul>

    <a href="{% url 'encuesta:detalle' pregunta.id %}"
      >¿Te gustaría votar de nuevo?</a
    ><br />
    <a href="{% url 'polls:index' %}">Volver al inicio</a>
  </body>
</html>